name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install @graphprotocol/graph-cli
      run: npm install -g @graphprotocol/graph-cli

    - name: test
      run: graph test -d
