name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install
      run: yarn install

    - name: Install @graphprotocol/graph-cli
      run: yarn global add @graphprotocol/graph-cli

    - name: Generate typings and build subgraph
      run: yarn codegen && yarn build

    - name: Test
      run: yarn test
