name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install
      run: npm install

    - name: Generate typings and build subgraph
      run: |
        graph codegen
        graph build

    - name: Test
      run: graph test -d
